### ISSUE TITLE
Map3d does not handle Zero indexed .fac files or matlab data (.mat) with zero indexed fields.

### ISSUE THREAD

**Issue by wgood** [SCIInstitute/map3d#17]
I have attached the Zero indexed geometries and well as the One indexed array. 
[Bug_Map3d.zip](https://github.com/SCIInstitute/map3d/files/269131/Bug_Map3d.zip)

**Comment by bryanworthen** [comment]
Hi, which version are you using? This should be fixed in 7.2.1.

**Comment by wgood** [comment]
Hello Bryan,

I forgot to update before sending the error off (and ultimately finding my mistake). Sorry for wasting your time on that one.

Cheers,
Wilson

**Comment by bryanworthen** [comment]
It's absolutely no problem. I just wanted to make sure it actually worked!
