### ISSUE TITLE
map3D doesn't work when we have large data

### ISSUE THREAD

**Issue by shayestehfard** [SCIInstitute/map3d#24]
map3D does not work when I have more than 100K samples for each channel.

**Comment by rsmacleod** [comment]
Hi, 
Can you subsample the data when you load it up (there is a command line option for this and also in the files window you should be able to control subsampling and also set the window of the data)?  I know this is not perfect but perhaps will work while we figure out where the problem is.   Also, can you place a sample data set somewhere that we can find it so that we are really working with the same data you are?
Best,
Rob

**Comment by jessdtate** [comment]
I tested this on my machine with some data that I made with 247 channels with ~1million samples.  The data (on the sci server at:  /home/sci/jess/software_testing/map3d/million_timesteps/) did load, however, it took much longer than SCIRun and matlab.  It took nearly 6 GB of RAM while loading, but the usage went back down to ~2 GB (the size of the data)   I'm running on an iMac os x 10.10. i5 32 GB RAM nvidia graphics (1024 mb).

**Comment by jessdtate** [comment]
I have a similar problem with mesh size, ie, loading big meshes takes much longer in map3d than in SCIRun or matlab.  There are some test meshes on the sci server (/home/sci/jess/software_testing/map3d/mesh_sizes).  The meshes that are ~ 100,000 faces (number in the filename) can load, though it takes a while.  I haven't tested the bigger meshes yet.  These are the binary versions, the ascii format takes much longer.  I'm testing on the same machine as above.

**Comment by bryanworthen** [comment]
(I don't know if replying by email attaches to comments - let's see :)

Thank you for trying the mac out.  I guess that proves that the mac build
is 64 bit out of the box, which is good. The windows build is not so
lucky.  I still have to figure out how to force windows to use 64bit opengl
and other libraries.

The data is ~250MB.  I tested loading it with windows, and it looks like it
does the following:

MatlabIO: read the file (250 MB - it's float data)
MatlabIO: uncompress the file (750 MB - I think it uses double data here)
map3d matlabIO interface - copy the array out of MatlabIO: ~1 GB
map3d: allocate a buffer to copy it into
map3d: allocate the SurfData array to copy that data into.
... at this point it crashes, exceeding the memory win32 is willing to let
you have.

That sounds pretty consistent with your testing - using 3x to 4x the memory
of the data.

I think I can eliminate 2, maybe 3 of those steps, AND pass in a linker
flag to map3d to let it go up to 3GB without fixing the 64 bit problem.
Then eventually fix the 64 bit problem.

Thanks,
Bryan

**Comment by bryanworthen** [comment]
Hi,

Can you let me know what OS you're running? It sounds like you're running Windows, since it looks like the Mac version seems to load the file.  I have reproduced what you're seeing on Windows, and I have created a pre-release 7.2.3 with a new windows build that I believe addresses the issue.  Would you please try it out?

**Comment by shayestehfard** [comment]
Hi,
I tried Map 3D version 7.2.2 and pre released version 7.2.3 on Windows. Still it does not work properly when I have large matlab data sizes. I have not tried it on  Mac Os, but I am going to try it soon.

**Comment by bryanworthen** [comment]
You're trying the same file that is attached to this issue? How are you loading the file (Command line or GUI? Are you only loading that file? What geometry are you loading with it?)

Thanks,
Bryan

**Comment by shayestehfard** [comment]
Hi Bryan, 
I tried Map3D with large data on mac and it works, but about 3 weeks ago I tried it on windows with same data and did not work. As the file size is large I couldn't attach it here. Please send me your email address to send you the files.

Best,
Kimia

**Comment by bryanworthen** [comment]
bryanworthen@gmail.com

**Comment by bryanworthen** [comment]
I'm working on making map3d a windows 64bit application.  Here is a screenshot from a prototype with 7 copies of your data file.  Once I get the installation package right, I'll attach a new version.
![7copies](https://cloud.githubusercontent.com/assets/1323758/22455830/2b277080-e74c-11e6-9267-aafff189fa73.png)

**Comment by shayestehfard** [comment]
Hi Bryan,
Thank you so much.

Best,
Kimia

**Comment by bryanworthen** [comment]
Hi - still working on the deployment of this.  Latest update - I pushed 7.2.3a which is a 64bit executable, but testing on a SCI windows machine indicated incorrect OpenGL libraries.  Working on tracking that down...

**Comment by bryanworthen** [comment]
7.2.4 is a 64bit executable, and I have confirmed it works on a SCI windows machine, and I opened 4 copies of the data file you supplied.  Please let me know if you still have trouble - if that is the case, please send me full reproduction steps (geometry files, and whether you used the command line or the Files dialog, and what the parameters were). Thanks.

**Comment by bryanworthen** [comment]
No known issues.
