### ISSUE TITLE
Graphic rendering issue with MacBooks with Retina display

### ISSUE THREAD

**Issue by AshishDoshi** [SCIInstitute/map3d#33]
Issue discovered during IBBM workshop/lab on Map3D.  When Map3D is run on Mac OS X on machines with retina display, all graphics (mesh, contours, time signal, colorbar) appear in the bottom-left quadrant of the view window.  The remainder of the window is black.  However, when the user interacts with the graphic, features of the graphic seem to occupy the entire window.  (For example, one can choose a node in the empty area of the view window.)

**Comment by bryanworthen** [comment]
Dup of #35.
