### ISSUE TITLE
In a display with a single surface, selecting global scaling crashes map3d

### ISSUE THREAD

**Issue by rsmacleod** [SCIInstitute/map3d#36]
A new bug (old versions do not have this one). When the user reads in a single surface with data, then selected "Scaling" --> "Range" --> "Global over all surfaces in one frame", the program crashes.  As soon as there are more surfaces, it all works fine.  And again, this does not happen with the 2016 version of map3d.

**Comment by bryanworthen** [comment]
Can you please specify which surf/data you're using? I have done dalepi with dipole2 and sock with cool1-atdr and I can do that without crashing.

**Comment by rsmacleod** [comment]
HI Bryan, How weird is this!  I cannot reproduce the error now. Lots of people in the class were having it and I think I am using the same mesh and potentials files.  Let me check with Wilson on this.

**Comment by wgood** [comment]
Hey All. I was having a hard time replicating this too. I was finally able to today. I will attach a zip with the pertinent files. The key is that you have to be displaying faces for the bug to happen. So if you are simply looking at edges the program will not crash. This seems to apply to all of the surfaces we had for IBBM (sock.mat, torso.mat, and map3dneedles.mat) with their corresponding data files. To get the bug: Load single geometry with data, render with surfaces (press s), and then change scaling to 'Global Across All Surfaces and Frames'

**Comment by wgood** [comment]
[Map3d_Bug.zip](https://github.com/SCIInstitute/map3d/files/1242947/Map3d_Bug.zip)

**Comment by bryanworthen** [comment]
Still can't reproduce (image of dataset with scaling)
![map3d0005](https://user-images.githubusercontent.com/1323758/29905640-24fe24b0-8dcd-11e7-9a93-2756f56f9916.png)

**Comment by bryanworthen** [comment]
Will try a few other things.

**Comment by bryanworthen** [comment]
Here's my command line (windows):
client\release\map3d.exe -f Map3d_Bug\Sock.mat -p Map3d_Bug\Run0076-cs.mat.

Are all of you using the mac version?

**Comment by rsmacleod** [comment]
I believe this was, indeed, a mac only bug.  Wilson?

**Comment by wgood** [comment]
I thought it was across all platforms. But it seems like that may not be the case. Let me go and get Gordon to test it. 


Cheers,
Wilson

**Comment by jessdtate** [comment]
If it helps, when I try to reproduce it, it doesn't crash right away, but the surface data disappears and colormap appears like it has no data.  If I hit the s key after that it crashes.

**Comment by wgood** [comment]
Hey All, 

I had Andrew reproduce this scaling bug on Windows 10. Not sure why you wouldn’t be seeing it Bryan. 

Cheers,
Wilson

**Comment by bryanworthen** [comment]
Could you perhaps send a movie of what you did to make it crash?
Bryan

**Comment by jessdtate** [comment]
Here are a couple movies that  show the crashes

[crash_bug_2.mov.zip](https://github.com/SCIInstitute/map3d/files/1289065/crash_bug_2.mov.zip)
[crash_bug.mov.zip](https://github.com/SCIInstitute/map3d/files/1289067/crash_bug.mov.zip)

**Comment by jessdtate** [comment]
perhaps the confusion is that the crash happens with "Global over all surfaces and frames".

**Comment by bryanworthen** [comment]
Thanks.  I can now reproduce the bug reliably.  Problem was I was loading
the files on the command line, and apparently using the File Dialog exposes
the crash.

**Comment by bryanworthen** [comment]
Please let me know if updating fixes this.  (Also please confirm that yours
worked via the command line.)

Thanks,
Bryan
